<!DOCTYPE html>
<html lang="en">
<#include "head.ftlh">
<body>

<#include "navbar.ftlh">

<div class="container-fluid text-center">
    <div class="row content">
        <div class="col-sm-2 sidenav">
        </div>
        <div class="col-sm-8 text-left">
            <h1 style="text-align: center">${message}</h1>
            <img style="text-align: center"
                 src="https://i.pinimg.com/originals/13/7c/a9/137ca9e2a4de70b11d0ae475997e8004.gif"
                 title="this slowpoke moves"/>


        </div>

    </div>
</div>

<#include "footer.ftlh">

</body>
</html>