<!doctype html>
<html lang="en">
<head>
    <title>Document</title>
</head>
<body>
<form action="/selection" method="get">

    Path:
    <input type="text" name="outFilePath"><br>
    Choice:
    <input type="text" name="choice"><br>
    FirstDate:
    <input type="text" name="firstDate"><br>
    LastDate:
    <input type="text" name="lastDate"><br>


    <input type="submit" value="Wyslij">
</form>


</body>
</html>